[package]
name = "roundhouse-provider"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
bytes = "1"
futures = "0.3"
roundhouse-core = { path = "../roundhouse-core" }
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
thiserror = "2.0.20"

[dev-dependencies]
tokio = { version = "1.53", features = ["full"] }
