//! `roundhouse-conformance` wiring for the `bedrock-converse` codec (§9.10).
//!
//! Cassette provenance: every `.cassette` file under
//! `testdata/cassettes/bedrock_converse/` is generated by
//! `examples/gen_bedrock_cassettes.rs`, whose module doc comment states
//! where the bytes come from (framing: `aws-smithy-eventstream`'s own
//! `write_message_to`, the same crate this codec decodes with; JSON payload
//! content: hand-authored against the fetched, verified AWS API Reference
//! field names). Regenerate with
//! `cargo run --example gen_bedrock_cassettes -p roundhouse-provider`.

use roundhouse_conformance::{checks, ConformanceCase, ConformanceSubject, SerializeOnlyMask};
use roundhouse_provider::codec::bedrock_converse::encode::encode;
use roundhouse_provider::codec::bedrock_converse::BedrockConverseProvider;
use roundhouse_provider::credential::CredentialProvider;
use roundhouse_provider::profile::ProviderProfile;
use roundhouse_provider::{
    CassetteTransport, ChatRequest, ChunkStrategy, ContentBlock, Provider, ProviderError,
    RequestCtx,
};
use roundhouse_secrets::credential::SigV4Credential;
use roundhouse_secrets::secret::Secret;
use std::sync::Arc;

#[path = "support/bedrock_converse_fixtures.rs"]
mod fixtures;

fn fixture_profile() -> ProviderProfile {
    toml::from_str(include_str!("../profiles/bedrock-converse.toml")).unwrap()
}

fn cassette_path(name: &str) -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/cassettes/bedrock_converse")
        .join(name)
}

/// A real `SigV4Credential` (fixed, obviously-fake test key material) --
/// `bedrock-converse` has no bare `api_key` fallback (REALITY-CORRECTIONS
/// §12b: SigV4 "applying" a credential to a request IS signing it), so
/// every test that drives `stream_chat` all the way through a cassette must
/// supply one.
fn test_credentials() -> Arc<dyn CredentialProvider> {
    Arc::new(SigV4Credential::new(
        "AKIAEXAMPLETESTKEY00000",
        Secret::new("wJalrXUtnFEMIexampleSECRETkey1234567890".to_string()),
        None,
        "us-east-1",
        "bedrock",
    ))
}

/// Maps one of `bedrock-converse.toml`'s own declared `[defaults.params]`
/// field identifiers onto the actual flattened wire-key path this codec's
/// `encode` emits for it. REALITY-CORRECTIONS §12c: the mask must be
/// *derived from the profile's own policy*, not hardcoded independently of
/// it -- this reads `profile.defaults.params.fields` directly (rather than
/// through `ParamsPolicy::allowed_fields`, whose `AllowOnly` arm returns
/// `self.fields` verbatim regardless of any wire-key list handed to it, so
/// calling it here would not do anything a plain field read doesn't already
/// do) and translates each declared identifier into this codec's actual
/// `inferenceConfig.*` camelCase path, so a change to the TOML's field list
/// changes what the mask permits.
fn params_wire_path(field: &str) -> &'static str {
    match field {
        "temperature" => "inferenceConfig.temperature",
        "top_p" => "inferenceConfig.topP",
        "max_tokens" => "inferenceConfig.maxTokens",
        "stop_sequences" => "inferenceConfig.stopSequences",
        other => panic!(
            "bedrock-converse.toml declares params field {other:?}, which this test's \
             wire-path translation table doesn't know about -- add it here"
        ),
    }
}

fn mask(profile: &ProviderProfile) -> SerializeOnlyMask {
    let mut allowed: Vec<String> = vec![
        "messages.role".into(),
        "messages.content".into(),
        "messages.content.text".into(),
        "messages.content.toolUse".into(),
        "messages.content.toolUse.toolUseId".into(),
        "messages.content.toolUse.name".into(),
        "messages.content.toolUse.input".into(),
        "messages.content.toolResult".into(),
        "messages.content.toolResult.toolUseId".into(),
        "messages.content.toolResult.content".into(),
        "messages.content.toolResult.content.text".into(),
        "messages.content.toolResult.status".into(),
        "system".into(),
        "system.text".into(),
        "toolConfig".into(),
        "toolConfig.tools".into(),
        "toolConfig.tools.toolSpec".into(),
        "toolConfig.tools.toolSpec.name".into(),
        "toolConfig.tools.toolSpec.description".into(),
        "toolConfig.tools.toolSpec.inputSchema".into(),
        "toolConfig.tools.toolSpec.inputSchema.json".into(),
        "toolConfig.tools.toolSpec.inputSchema.json.$schema".into(),
        "toolConfig.tools.toolSpec.inputSchema.json.title".into(),
        "toolConfig.tools.toolSpec.inputSchema.json.type".into(),
        "toolConfig.toolChoice".into(),
        "toolConfig.toolChoice.tool".into(),
        "toolConfig.toolChoice.tool.name".into(),
        "toolConfig.toolChoice.any".into(),
        "inferenceConfig".into(),
    ];
    for field in &profile.defaults.params.fields {
        allowed.push(params_wire_path(field).to_string());
    }
    SerializeOnlyMask {
        mandatory: vec!["messages".into()],
        allowed,
    }
}

struct BedrockConverseSubject;

impl ConformanceSubject for BedrockConverseSubject {
    type Provider = BedrockConverseProvider;

    fn provider() -> Self::Provider {
        BedrockConverseProvider::new(fixture_profile())
    }

    fn cases() -> Vec<ConformanceCase> {
        let mask = mask(&fixture_profile());
        // `tools`/`parallel_tools`: the request's user-turn `Text` block is
        // never expected to survive into a ToolUse-only assistant response.
        let text_not_expected_in_a_tool_call_response = vec![
            "the request's Text prompt does not appear in a ToolUse-only response".to_string(),
        ];
        vec![
            ConformanceCase {
                name: "text",
                request: fixtures::single_turn_text(),
                cassette_path: cassette_path("text.cassette"),
                mask: mask.clone(),
                declared_loss_events: vec![],
                expected_error: None,
            },
            ConformanceCase {
                name: "tools",
                request: fixtures::forced_tool_choice(),
                cassette_path: cassette_path("tools.cassette"),
                mask: mask.clone(),
                declared_loss_events: text_not_expected_in_a_tool_call_response.clone(),
                expected_error: None,
            },
            ConformanceCase {
                name: "parallel_tools",
                request: fixtures::parallel_tool_calls(),
                cassette_path: cassette_path("parallel_tools.cassette"),
                mask: mask.clone(),
                declared_loss_events: text_not_expected_in_a_tool_call_response,
                expected_error: None,
            },
            // Decode-focused case (see `fixtures::single_turn_text`'s reuse
            // here and this crate's `bedrock_converse::mod` doc comment):
            // this profile's only declared model has no reasoning control on
            // the *request* side (verified: Bedrock's base Converse schema
            // has no generic reasoning field at all), but the *response*
            // side must still correctly decode a `reasoningContent` block
            // when a reasoning-capable model emits one -- proven by this
            // cassette, independent of what the request asked for.
            ConformanceCase {
                name: "reasoning",
                request: fixtures::single_turn_text(),
                cassette_path: cassette_path("reasoning.cassette"),
                mask: mask.clone(),
                declared_loss_events: vec![],
                expected_error: None,
            },
            ConformanceCase {
                name: "error_429",
                request: fixtures::single_turn_text(),
                cassette_path: cassette_path("error_429.cassette"),
                mask: mask.clone(),
                declared_loss_events: vec![],
                expected_error: Some(|e| matches!(e, ProviderError::RateLimited { .. })),
            },
            ConformanceCase {
                name: "error_500",
                request: fixtures::single_turn_text(),
                cassette_path: cassette_path("error_500.cassette"),
                mask: mask.clone(),
                declared_loss_events: vec![],
                expected_error: Some(|e| matches!(e, ProviderError::Server { status: 500 })),
            },
            // Bonus, beyond the required minimum: a genuine in-band
            // eventstream exception frame (`:message-type: exception`)
            // arriving mid-generation, after partial content already
            // streamed -- proves it surfaces as an error via this profile's
            // own `[errors]` table (`ThrottlingException` ->
            // `shed_concurrency` -> `RateLimited`), not a silently truncated
            // success.
            ConformanceCase {
                name: "exception_throttling",
                request: fixtures::single_turn_text(),
                cassette_path: cassette_path("exception_throttling.cassette"),
                mask,
                declared_loss_events: vec![],
                expected_error: Some(|e| matches!(e, ProviderError::RateLimited { .. })),
            },
        ]
    }

    fn wire_body(req: &ChatRequest) -> serde_json::Value {
        encode(req, &fixture_profile())
    }
}

/// The 4 chunk boundaries every case is replayed at -- mirrors
/// `roundhouse_conformance::checks`'s private `CHUNK_STRATEGIES` constant
/// (not `pub`, so it can't be reused directly; see this file's module doc
/// comment on why this test doesn't call `roundhouse_conformance::run`
/// unchanged).
const CHUNK_STRATEGIES: [ChunkStrategy; 4] = [
    ChunkStrategy::WholeBody,
    ChunkStrategy::Fixed(1),
    ChunkStrategy::Fixed(3),
    ChunkStrategy::Prime(17),
];

fn extract_request_blocks(req: &ChatRequest) -> Vec<ContentBlock> {
    req.messages
        .iter()
        .flat_map(|m| m.content.clone())
        .collect()
}

/// Replays `case` against its cassette at every [`CHUNK_STRATEGIES`] entry
/// and asserts the folded result is identical across all of them --
/// functionally identical to
/// `roundhouse_conformance::checks::check_fold_determinism`, reimplemented
/// here ONLY because that function hardcodes `RequestCtx { credentials:
/// None, .. }` internally with no way to override it (see this file's module
/// doc comment: `roundhouse-conformance`'s shared harness has no path for a
/// credential-REQUIRED provider like `bedrock-converse`, which has no bare
/// `api_key` fallback to fall back to). Every other check
/// (`check_mask`/`check_round_trip_fidelity`/`check_usage_invariants`) is
/// still the genuine, shared, unmodified `roundhouse_conformance::checks`
/// function.
async fn check_fold_determinism_with_credentials(
    provider: &BedrockConverseProvider,
    case: &ConformanceCase,
) -> (Vec<String>, Option<checks::FoldedResult>) {
    let mut failures = Vec::new();
    let mut results: Vec<checks::FoldedResult> = Vec::new();

    for strategy in CHUNK_STRATEGIES {
        let transport = match CassetteTransport::from_file(&case.cassette_path, strategy) {
            Ok(t) => t,
            Err(e) => {
                failures.push(format!(
                    "could not load cassette {} for chunk strategy {strategy:?}: {e}",
                    case.cassette_path.display()
                ));
                continue;
            }
        };
        let ctx = RequestCtx {
            trace_id: None,
            transport: Arc::new(transport),
            api_key: "unused-bare-key".into(),
            credentials: Some(test_credentials()),
        };
        match (
            provider.stream_chat(&case.request, &ctx).await,
            case.expected_error,
        ) {
            (Ok(_), Some(_)) => failures.push(format!(
                "expected stream_chat to fail replaying cassette {} at chunk strategy \
                 {strategy:?}, but it returned a successful stream",
                case.cassette_path.display()
            )),
            (Ok(stream), None) => results.push(checks::fold_stream(stream).await),
            (Err(e), Some(predicate)) => {
                if !predicate(&e) {
                    failures.push(format!(
                        "stream_chat failed replaying cassette {} at chunk strategy \
                         {strategy:?}, but the error didn't match the declared \
                         expected_error predicate: {e}",
                        case.cassette_path.display()
                    ));
                }
            }
            (Err(e), None) => failures.push(format!(
                "stream_chat failed replaying cassette {} at chunk strategy {strategy:?}: {e}",
                case.cassette_path.display()
            )),
        }
    }

    for pair in results.windows(2) {
        if serde_json::to_value(&pair[0].blocks).ok() != serde_json::to_value(&pair[1].blocks).ok()
            || serde_json::to_value(&pair[0].usage).ok()
                != serde_json::to_value(&pair[1].usage).ok()
            || pair[0].loss_events != pair[1].loss_events
        {
            failures.push(format!(
                "fold determinism violated for cassette {}: folded result differs between \
                 chunk strategies",
                case.cassette_path.display()
            ));
        }
    }

    (failures, results.into_iter().next())
}

#[tokio::test]
async fn bedrock_converse_is_conformant() {
    let provider = BedrockConverseProvider::new(fixture_profile());
    let mut failures = Vec::new();

    for case in BedrockConverseSubject::cases() {
        let wire_body = BedrockConverseSubject::wire_body(&case.request);
        failures.extend(checks::check_mask(&wire_body, &case.mask));

        let (det_failures, folded) =
            check_fold_determinism_with_credentials(&provider, &case).await;
        failures.extend(det_failures);

        if let Some(result) = folded {
            failures.extend(checks::check_round_trip_fidelity(
                &extract_request_blocks(&case.request),
                &result.blocks,
                &case.declared_loss_events,
            ));
            failures.extend(checks::check_usage_invariants(&result.usage));
        }
    }

    assert!(
        failures.is_empty(),
        "conformance suite failures:\n{}",
        failures.join("\n")
    );
}

/// `Result::expect_err` needs `T: Debug`, and `ChatStream` deliberately isn't
/// -- matches `conformance_openai_responses.rs`'s identical precedent.
fn expect_err(result: Result<roundhouse_provider::ChatStream, ProviderError>) -> ProviderError {
    match result {
        Ok(_) => panic!("expected an error, got a successful stream"),
        Err(err) => err,
    }
}

async fn provider_ctx_pair(cassette: &str) -> (BedrockConverseProvider, RequestCtx) {
    let transport =
        CassetteTransport::from_file(&cassette_path(cassette), ChunkStrategy::WholeBody)
            .unwrap_or_else(|e| panic!("{cassette} must parse: {e}"));
    let ctx = RequestCtx {
        trace_id: None,
        transport: Arc::new(transport),
        api_key: "unused-bare-key".into(),
        credentials: Some(test_credentials()),
    };
    (BedrockConverseProvider::new(fixture_profile()), ctx)
}

/// REALITY-CORRECTIONS §14g: proves `bedrock-converse.toml`'s own `[errors]`
/// table is actually consulted, not merely deserialized and ignored.
/// Deliberately status 400 (matches `profile_errors_wiring_test.rs` and
/// `conformance_openai_responses.rs`'s identical precedent): 429/500 already
/// have their own entries in `classify`'s generic HTTP-status fallback tier,
/// so a same-status test would pass even if this profile's table were never
/// read at all.
#[test]
fn bedrock_converse_error_table_throttling_exception_maps_to_rate_limited() {
    let error_profile = fixture_profile().error_profile();
    let body = serde_json::to_vec(&serde_json::json!({
        "error": { "type": "ThrottlingException", "message": "slow down" }
    }))
    .unwrap();
    let classified =
        roundhouse_provider::errors::classify(&error_profile, 400, &body, &http::HeaderMap::new());
    assert!(
        matches!(classified, ProviderError::RateLimited { .. }),
        "expected RateLimited, got {classified:?}"
    );
}

#[test]
fn bedrock_converse_error_table_model_error_exception_maps_to_overloaded() {
    let error_profile = fixture_profile().error_profile();
    let body = serde_json::to_vec(&serde_json::json!({
        "error": { "type": "ModelErrorException", "message": "model choked" }
    }))
    .unwrap();
    let classified =
        roundhouse_provider::errors::classify(&error_profile, 400, &body, &http::HeaderMap::new());
    assert!(
        matches!(classified, ProviderError::Overloaded),
        "expected Overloaded, got {classified:?}"
    );
}

#[test]
fn bedrock_converse_error_table_access_denied_exception_maps_to_quota_exhausted() {
    let error_profile = fixture_profile().error_profile();
    let body = serde_json::to_vec(&serde_json::json!({
        "error": { "type": "AccessDeniedException", "message": "no access" }
    }))
    .unwrap();
    let classified =
        roundhouse_provider::errors::classify(&error_profile, 400, &body, &http::HeaderMap::new());
    assert!(
        matches!(classified, ProviderError::QuotaExhausted),
        "expected QuotaExhausted (bedrock-converse.toml's own choice for AccessDeniedException, \
         see the profile's [errors] table comment), got {classified:?}"
    );
}

#[tokio::test]
async fn error_429_cassette_classifies_via_the_x_amzn_errortype_header_remap() {
    let (provider, ctx) = provider_ctx_pair("error_429.cassette").await;
    let err = expect_err(
        provider
            .stream_chat(&fixtures::single_turn_text(), &ctx)
            .await,
    );
    assert!(
        matches!(err, ProviderError::RateLimited { .. }),
        "got {err:?}"
    );
}

/// §9.8: "never `?` on JSON parsing in the error path" -- a raw HTML 500
/// (no `x-amzn-errortype` header at all) must classify via the HTTP-status
/// fallback tier without panicking on JSON decode.
#[tokio::test]
async fn error_500_html_body_classifies_as_server_error_without_panicking() {
    let (provider, ctx) = provider_ctx_pair("error_500.cassette").await;
    let err = expect_err(
        provider
            .stream_chat(&fixtures::single_turn_text(), &ctx)
            .await,
    );
    assert!(
        matches!(err, ProviderError::Server { status: 500 }),
        "got {err:?}"
    );
}

/// The in-band exception path end to end, outside the generic harness (pins
/// the exact wire pipeline with a plain assertion): partial content
/// streamed, then a real `ThrottlingException` eventstream frame -- must
/// classify as `RateLimited` via this profile's own `[errors]` table, and
/// must NOT emit a `MessageStop` for the partial content that streamed
/// before the exception arrived.
#[tokio::test]
async fn exception_throttling_cassette_is_an_error_not_a_truncated_success() {
    let (provider, ctx) = provider_ctx_pair("exception_throttling.cassette").await;
    let err = expect_err(
        provider
            .stream_chat(&fixtures::single_turn_text(), &ctx)
            .await,
    );
    assert!(
        matches!(err, ProviderError::RateLimited { .. }),
        "got {err:?}"
    );
}

/// A transport that panics if `send` is ever called -- proves a request
/// with content this codec cannot encode is rejected before any network I/O.
struct PanicsIfCalledTransport;

impl roundhouse_provider::HttpTransport for PanicsIfCalledTransport {
    fn send<'a>(
        &'a self,
        _req: roundhouse_provider::HttpRequest,
    ) -> futures::future::BoxFuture<
        'a,
        Result<roundhouse_provider::HttpResponseStream, roundhouse_provider::TransportError>,
    > {
        panic!(
            "stream_chat must reject unencodable content before ever calling HttpTransport::send"
        )
    }
}

#[tokio::test]
async fn stream_chat_rejects_a_reasoning_request_before_any_transport_call() {
    let ctx = RequestCtx {
        trace_id: None,
        transport: Arc::new(PanicsIfCalledTransport),
        api_key: "unused".into(),
        credentials: None,
    };
    let provider = BedrockConverseProvider::new(fixture_profile());
    let err = expect_err(provider.stream_chat(&fixtures::reasoning_on(), &ctx).await);
    assert!(matches!(err, ProviderError::Unsupported(_)), "got {err:?}");
}

/// REALITY-CORRECTIONS §12b: a missing `CredentialProvider` must fail
/// closed locally, never send an unauthenticated request to the wire.
#[tokio::test]
async fn stream_chat_rejects_a_missing_credential_provider_before_any_transport_call() {
    let ctx = RequestCtx {
        trace_id: None,
        transport: Arc::new(PanicsIfCalledTransport),
        api_key: "unused".into(),
        credentials: None,
    };
    let provider = BedrockConverseProvider::new(fixture_profile());
    let err = expect_err(
        provider
            .stream_chat(&fixtures::single_turn_text(), &ctx)
            .await,
    );
    assert!(matches!(err, ProviderError::Unsupported(_)), "got {err:?}");
}
