[package]
name = "roundhouse-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
roundhouse-core = { path = "../roundhouse-core" }
rusqlite = { workspace = true }
rusqlite_migration = { workspace = true }
deadpool-sqlite = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
